// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: xCommond.proto

#include "xCommond.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
static const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* file_level_enum_descriptors_xCommond_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_xCommond_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_xCommond_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_xCommond_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016xCommond.proto*\325\003\n\007CmdType\022\023\n\017PB_SMANA"
  "GER_CMD\020d\022\024\n\020PB_SLAUNCHER_CMD\020e\022\025\n\021PB_DA"
  "TARECORD_CMD\020f\022\025\n\021PB_LOGIN_GATE_CMD\020g\022\025\n"
  "\021PB_LOBBY_GATE_CMD\020h\022\027\n\023PB_LOBBY_CENTER_"
  "CMD\020i\022\020\n\014PB_MATCH_CMD\020j\022\021\n\rPB_FRIEND_CMD"
  "\020k\022\023\n\017PB_FM_ROUTE_CMD\020l\022\017\n\013PB_CHAT_CMD\020m"
  "\022\021\n\rPB_BATTLE_CMD\020x\022\022\n\rPB_MARKET_CMD\020\202\001\022"
  "\020\n\013PB_MAIL_CMD\020\214\001\022\023\n\016PB_GAMELOG_CMD\020\226\001\022\020"
  "\n\013PB_HOME_CMD\020\240\001\022\031\n\024PB_BATTLE_REPORT_CMD"
  "\020\245\001\022\020\n\013PB_SLOG_CMD\020\252\001\022\027\n\022PB_SG_OPERAROR_"
  "CMD\020\253\001\022\016\n\tPB_GM_CMD\020\262\001\022\024\n\017PB_GAMELOAD_CM"
  "D\020\264\001\022\027\n\022PB_SERVER_LOAD_CMD\020\276\001\022\021\n\014PB_GUIL"
  "D_CMD\020\310\001"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_xCommond_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_xCommond_2eproto = {
  false, false, 488, descriptor_table_protodef_xCommond_2eproto, "xCommond.proto", 
  &descriptor_table_xCommond_2eproto_once, nullptr, 0, 0,
  schemas, file_default_instances, TableStruct_xCommond_2eproto::offsets,
  nullptr, file_level_enum_descriptors_xCommond_2eproto, file_level_service_descriptors_xCommond_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_xCommond_2eproto_getter() {
  return &descriptor_table_xCommond_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_xCommond_2eproto(&descriptor_table_xCommond_2eproto);
const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* CmdType_descriptor() {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_xCommond_2eproto);
  return file_level_enum_descriptors_xCommond_2eproto[0];
}
bool CmdType_IsValid(int value) {
  switch (value) {
    case 100:
    case 101:
    case 102:
    case 103:
    case 104:
    case 105:
    case 106:
    case 107:
    case 108:
    case 109:
    case 120:
    case 130:
    case 140:
    case 150:
    case 160:
    case 165:
    case 170:
    case 171:
    case 178:
    case 180:
    case 190:
    case 200:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
